version: "3.9"
services:
  api:
    build: ./Api
    depends_on:
      - identityserver
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Api.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - AUTHENTICATION__AUTHORITY=https://identityserver
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
  consoleapplication:
    build: ./ConsoleApplication
    depends_on:
      - api
      - identityserver
    entrypoint: /bin/sh -c "sleep 10 && update-ca-certificates && dotnet ConsoleApplication.dll"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - API_URL=https://api
      - AUTHENTICATION__AUTHORITY=https://identityserver
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  identityserver:
    build: ./IdentityServer
    depends_on:
      - db
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet IdentityServer.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=db;Port=5432;Database=identityserver;User Id=postgres;Password=password;
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
volumes:
  db:
